shoppinglister/models/item.py
from datetime import datetime


class Item:
    """ Item defines the properties of ordinary shopping list items"""


    def __init__(self, item_id, name, price, quantity):
        self.item_id = item_id
        self.name = name
        self.price = price
        self.quantity = quantity
        self.date_added = datetime.now().strftime("%Y-%m-%d %H:%M")

shoppinglister/models/shoppinglist.py
from datetime import datetime


class ShoppingList:
    def __init__(self, list_id, name, notify_date):
        self.list_id = list_id
        self.name = name
        # date on which to remind the owner of the shopping list
        self.notify_date = notify_date
        self.items = dict()  # dictionary of Items and their IDs (ID: Item)
        self.item_names = dict()  # mapping item names and their IDs (ID: name)
        self.date_created = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.date_modified = self.date_created

    def add_item(self, item):
        """ add_item adds an item to the shopping list. No duplicates allowed
        :returns True if item has been added, False otherwise
        """
        if item.item_id in self.items.keys() or item.name in self.item_names.values():
            return False

        self.items[item.item_id] = item
        self.item_names[item.item_id] = item.name.title()
        self.date_modified = datetime.now().strftime("%Y-%m-%d %H:%M")
        return True

    def remove_item(self, item_id):
        """ Deletes an item from the ShoppingList:
        :param item_id string
        :returns True if item_id exists and has been removed
        False if item with that id hasn't been found
        """
        removed = False
        if item_id in self.items:
            del self.items[item_id]
            del self.item_names[item_id]
            self.date_modified = datetime.now().strftime("%Y-%m-%d %H:%M")
            removed = True
            self.date_modified = datetime.now().strftime("%Y-%m-%d %H:%M")
        return removed

    def get_item(self, item_id):
        """ Returns an item specified by item_id"""
        if item_id in self.items:
            return self.items[item_id]
        return None

    def edit_item(self, item_id, new_name, quantity, price):
        """ Edits an item's fields by using its name """

        for id, old_name in self.item_names.items():
            """If we have beans, say on a particular shopping list,
            we shouldn't edit another item to be called beans too. Just to keep the list clean"""
            if old_name == new_name.title() and item_id != id:
                return False

        has_been_edited = False
        if item_id in self.items:
            old_item = self.items[item_id]
            old_item.name = new_name.title()
            old_item.quantity = quantity
            old_item.price = price
            has_been_edited = True
            self.date_modified = datetime.now().strftime("%Y-%m-%d %H:%M")
        return has_been_edited

shoppinglister/views.py
from flask import Blueprint, request, flash, redirect, render_template, url_for, session
from shoppinglister.models.user import User
from shoppinglister.models.shoppinglist import ShoppingList
from shoppinglister.models.item import Item
from shoppinglister.models.mainapp import App

lister = Blueprint("lister", __name__)

app_instance = App()


@lister.route("/")
@lister.route("/signup", methods=['GET', 'POST'])
def signup():
    """ Defines routes for signing up a new user. """
    error = None

    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        password = request.form["password"]
        confirm_password = request.form["confirm_password"]

        if password != confirm_password:
            return render_template("signup.html", error="Password mismatch! please try again")

        if name and email and password and confirm_password:
            user = User(name, email, password)
            # if a user has just been registered, then, ...
            if app_instance.register(user):
                flash("You have been registered")
                return redirect(url_for("lister.login"))
            error = f"User with email \"{email}\" already exists!!, try logging in"
    return render_template("signup.html", error=error)


@lister.route("/login", methods=["GET", "POST"])
def login():
    """
    Login is the entry point of the application. Without logging in,
    the core functionality of this application remains hidden.
    The route `/login` is used for this cause.
    """

    # if user is already logged in, redirect them to the home page.
    if session.get("logged_in"):
        return redirect(url_for("lister.shopping_list"))

    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        if email and password:
            if app_instance.login(email, password):
                session["logged_in"] = True
                session['email'] = email
                return redirect(url_for("lister.shopping_list"))
            error = "Wrong email or password. Try Again"
            return render_template("login.html", error=error)
    return render_template("login.html")


@lister.route("/view/list")
def shopping_list():
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    return render_template("shopping_list.html", shoppinglists=user.shoppinglists, user=user)


@lister.route("/add/list", methods=["POST"])
def add_list():
    """ Defines routes for adding new shopping lists to the application. """
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    name = request.form["name"]
    notify_date = request.form["notify_date"]
    if name and notify_date:
        list_id = app_instance.generate_ID()
        if user.create_shoppinglist(ShoppingList(list_id, name, notify_date)):
            flash(f"A list with name  {name.capitalize()} has been created successfully")
            return redirect(url_for("lister.shopping_list"))
        flash(
            f"A List with ID {list_id} already exists! You may use another ID or add new items to the existing one")
    else:
        flash("Both fields required: please try again")

    return render_template("shopping_list.html", shoppinglists=user.shopping_lists, user=user)


@lister.route("/edit/list/<list_id>", methods=["POST", "GET"])
def edit_list(list_id):
    """ edit_list defines routes for editing shopping lists with in the application"""
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))

    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(list_id)
    if not shoppinglist:
        flash("That list doesn't exist")
        return redirect(url_for("lister.shopping_list"))

    if request.method == "POST":
        name = request.form["name"]
        notify_date = request.form["notify_date"]
        if not name or not notify_date:
            flash("Both fields required! Enter name and the notification date")
        else:
            if user.edit_shoppinglist(list_id, name, notify_date):
                flash(f"The list has been edited successfully")
                return redirect(url_for("lister.shopping_list"))
            flash("Unable to edit list")
    return render_template("edit_list.html", user=user, shoppinglist=shoppinglist)


@lister.route("/delete/list/<list_id>", methods=["GET", "POST"])
def delete_list(list_id):
    """delete_list defines routes for deleting a
    shopping list from a specified user account """
    error = None
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(list_id)
    if not shoppinglist:
        return redirect(url_for("lister.shopping_list"))
    if request.method == "POST":
        if user.delete_shoppinglist(list_id):
            flash(f"List with {list_id} has been deleted successfully")
            return redirect(url_for("lister.delete_list", list_id=shoppinglist.list_id))
        error = f"Failed to delete {list_id}"
    return render_template("delete_list.html", error=error, shoppinglist=shoppinglist, user=user)


@lister.route("/view/list/items/<list_id>", methods=["POST", "GET"])
def items(list_id):
    """ Handles the display of all items with in a particular list"""
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(
        list_id)  # returns a list of shop_items
    if not shoppinglist:
        return redirect(url_for("lister.shopping_list"))
    return render_template("items.html", user=user, shoppinglist=shoppinglist)


@lister.route("/add/list/item/<list_id>", methods=["POST"])
def add_item(list_id):
    """ defines routes for adding an item to a list"""
    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(list_id)

    name = request.form["name"]
    quantity = request.form["quantity"]
    price = request.form["price"]
    if not name or not quantity or not price:
        flash("All fields required: please recheck your inputs")
    else:

        item = Item(app_instance.generate_ID(), name, price, quantity)
        if shoppinglist.add_item(item):
            flash(f"{name} added successfully")
            return redirect(url_for("lister.items", list_id=list_id))
        flash(
            f"An item with name {name} already exists. Try editing it's price and quantity")
    return render_template("items.html", user=user, shoppinglist=shoppinglist)


@lister.route("/edit/list/item/<list_id>/<item_id>", methods=["GET", "POST"])
def edit_item(list_id, item_id):
    """ edit_item defines routes for editing an item within a list """

    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))
    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(list_id)
    item = shoppinglist.get_item(item_id)
    if not shoppinglist or not item:
        flash(f"Item doesn't exist on the mentioned shopping list")
        return redirect(url_for("lister.items", list_id=list_id))

    if request.method == "POST":
        name = request.form["name"]
        quantity = request.form["quantity"]
        price = request.form["price"]
        if name and quantity and price:
            if shoppinglist.edit_item(item_id, name, quantity, price):
                flash(f"Item has successfully been edited")
                return redirect(url_for("lister.items", list_id=list_id))
            flash("Failed to edit item")
        else:
            flash("All inputs required, recheck your inputs and try again!")
    return render_template("edit_items.html", user=user, shoppinglist=shoppinglist, item=item)


@lister.route("/delete/list/item/<list_id>/<item_id>", methods=["GET", "POST"])
def delete_item(list_id, item_id):
    """ Defines routes for removing an item from a specified list """
    error = None

    if not session.get("logged_in"):
        flash("Please first login!")
        return redirect(url_for("lister.login"))

    user = app_instance.get_user(session["email"])
    shoppinglist = user.get_shoppinglist(list_id)
    item = shoppinglist.get_item(item_id)

    if not item or not shoppinglist:
        flash("Item doesn't exist on the shopping list with that name")
        return redirect(url_for("lister.items", list_id=list_id))

    if request.method == "POST":
        if shoppinglist.remove_item(item_id):
            flash("Item has successfully been deleted")
            return redirect(url_for("lister.items", list_id=shoppinglist.list_id))
        error = "Item has not been deleted"
    return render_template("delete_item.html", error=error, user=user, shoppinglist=shoppinglist, item=item)


@lister.route("/logout")
def logout():
    if session.get("logged_in"):
        session["logged_in"] = False
        del session["email"]
    return redirect(url_for("lister.signup"))

shoppinglister/templates/delete_item.html
{% extends "base.html" %} {% block title %}Delete Item{% endblock %} {% block content %}

<body>
    <nav class="navbar navbar-inverse fixed-top bg-faded navbar-toggleable-sm ">
        <div class="container">
            <a href="{{ url_for('lister.shopping_list') }}" class="navbar-brand m-o align-content-end mr-auto">
                Shopping Lister
            </a>
            <div class="navbar-nav ">
                <a class="nav-item nav-link" href="#">{{ user.email }}</a>
                <a class="nav-item nav-link" href="{{ url_for('lister.logout') }}">Log Out</a>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">

            <form class="col" action="{{ url_for('lister.delete_item', list_id = shoppinglist.list_id, item_id = item.item_id) }}" method="post">
                <div class="container new_list_background card col-6">
                    <h2 class="text-capitalize card-title mt-1"> Delete </h2>
                    <div class="row">
                        <div class="col">
                            <div class="btn-group mb-5">
                                <div>
                                    <p>Are you sure you want to delete this item?</p>
                                    <button class="btn btn-danger"> Delete</button>
                                    <a href="{{ url_for('lister.items', list_id=shoppinglist.list_id) }}" class="btn btn-secondary ">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</body>
{% endblock %}

shoppinglister/templates/edit_items.html
{% extends "base.html" %} {% block title %}Edit Item{% endblock %} {% block content %}

<body>

    <!-- header navigation bar -->
    <nav class="navbar navbar-inverse fixed-top bg-faded navbar-toggleable-sm ">
        <div class="container">
            <a href="{{ url_for('lister.shopping_list') }}" class="navbar-brand m-o align-content-end mr-auto">
                Shopping Lister
            </a>
            <div class="navbar-nav ">
                {% if user %}
                <a class="nav-item nav-link" href="#">{{ user.email }}</a> {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('lister.logout') }}">Log Out</a>
            </div>
        </div>
    </nav>

    <!-- Editing an item -->
    <div class="container">
        {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
        <div class="alert alert-success alert-dismissable offset-2">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}

        <div class="row">
            <div class="container new_list_background card col-6">
                <form action="{{ url_for('lister.edit_item', list_id=shoppinglist.list_id, item_id=item.item_id) }}" method="post">
                    <h2 class="text-capitalize card-title mt-1">Edit List Item</h2>
                    <div class="row">
                        <div class="col">
                            <!-- name-->
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Item</label>
                                <div class="col">
                                    <input class="form-control" id="name" name="name" value="{{ item.name }}" required>
                                </div>
                            </div>

                            <!--quantity-->
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="quantity">Quantity</label>
                                <div class="col">
                                    <input class="form-control" id="quantity" name="quantity" value="{{ item.quantity }}" required>
                                </div>
                            </div>

                            <!--price-->
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="price">Price</label>
                                <div class="col">
                                    <input class="form-control" id="price" name="price" value="{{ item.price }}" required>
                                </div>
                            </div>
                            <!--save button-->
                            <div class="form-group">
                                <div>
                                    <button class="btn btn-success ">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}

shoppinglister/templates/edit_list.html
{% extends "base.html" %} {% block title %}Edit List{% endblock %} {% block content %}

<body>
    <nav class="navbar navbar-inverse fixed-top bg-faded navbar-toggleable-sm ">
        <div class="container">
            <a href="{{ url_for('lister.shopping_list') }}" class="navbar-brand m-o align-content-end mr-auto">
                Shopping Lister
            </a>
            <div class="navbar-nav ">
                <a class="nav-item nav-link" href="#">{{ user.email }}</a>
                <a class="nav-item nav-link" href="{{ url_for('lister.logout') }}"> Log Out </a>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <!--flash message-->
            {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
            <div class="alert alert-success alert-dismissable offset-2">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> {{ message }}
            </div>
            {% endfor %} {% endif %} {% endwith %}

            <!--error -->
            {% if error %}
            <div class="d-flex justify-content-center alert alert-danger alert-dismissable offset-3 col-6">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <p class="error">{{ error }}</p>
            </div>
            {% endif %}

            <div class="container new_list_background card col-6">
                <form action="{{ url_for('lister.edit_list', list_id=shoppinglist.list_id) }}" method="post">
                    <h2 class="text-capitalize card-title mt-1">Edit shopping list</h2>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <div class="col">
                                    <label class="control-label col-sm-2" for="name">Name:</label>
                                </div>
                                <div class="col">
                                    <input class="form-control" id="name" name="name" value="{{ shoppinglist.name }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col">
                                    <label class="control-label col-sm-2" for="notify_date">Remind me on:</label>
                                </div>
                                <div class="col">
                                    <label>
                                        <input type="date" name="notify_date" value="{{ shoppinglist.notify_date }}"
                                               required>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    <button class="btn btn-success">Save</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
{% endblock %}

shoppinglister/templates/items.html
{% extends "base.html" %} {% block title %}Items {% endblock %} {% block content %}

<body>

    <nav class="navbar navbar-inverse fixed-top bg-faded navbar-toggleable-sm ">
        <div class="container">
            <a href="{{ url_for('lister.shopping_list') }}" class="navbar-brand m-o align-content-end mr-auto">
                Shopping Lister
            </a>
            <div class="navbar-nav ">
                <a class="nav-item nav-link" href="#">{{ user.email }}</a>
                <a class="nav-item nav-link" href="{{ url_for('lister.logout') }}"> Log Out </a>
            </div>
        </div>
    </nav>

    <div class="container items">
        <div class="float-right mb-5">
            <div class="row">
                <div class="col">
                    <button class=" btn btn-success" data-toggle="modal" data-target="#myModal">Add Items
                    </button>
                </div>
            </div>
        </div>

        {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
        <div class="alert alert-success alert-dismissable offset-3 col-6">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}

        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Item</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span>&times;</span>
                        </button>
                    </div>

                    <!-- modal body-->
                    <div class="modal-body">
                        <form class="form-horizontal" action="{{ url_for('lister.add_item', list_id=shoppinglist.list_id) }}" method="post">
                            <div class="row">
                                <div class="col">

                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="name">Name</label>
                                        <div class="col">
                                            <input class="form-control" id="name" name="name" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="quantity">Quantity</label>
                                        <div class="col">
                                            <input class="form-control" id="quantity" name="quantity" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="price">Price</label>
                                        <div class="col">
                                            <input class="form-control" id="price" name="price" required>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <input type="submit" class="btn btn-success" value="Save">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <!-- Table displaying list items-->
        {% if shoppinglist %}
        <table class="table table-hover">

            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th colspan="2" class="text-md-center">Action</th>
                </tr>
            </thead>

            <tbody>
                {% for id, item in shoppinglist.items.items() %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.price }}</td>
                    <td class="text-right"><a href="{{ url_for('lister.edit_item', list_id=shoppinglist.list_id, item_id=item.item_id) }}" class="btn btn-link">edit</a></td>
                    <td class="text-right"><a href="{{ url_for('lister.delete_item', list_id=shoppinglist.list_id, item_id=item.item_id) }}" class="btn btn-link">delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}

        <h1 class="text-center d-flex align-item-center justify-content-center">There are no items in {{ shoppinglist.name }} </h1>
        {% endif %}
    </div>
</body>
{% endblock %}

shoppinglister/templates/shopping_list.html
{% extends "base.html" %} {% block title %}My Lists{% endblock %} {% block content %}

<body>
    <nav class="navbar navbar-inverse fixed-top bg-faded navbar-toggleable-sm ">
        <div class="container">
            <a href="{{ url_for('lister.shopping_list') }}" class="navbar-brand m-o align-content-end mr-auto">
                Shopping Lister
            </a>

            <div class="navbar-nav ">
                <a class="nav-item nav-link" href="#">{{ user.email }}</a>
                <a class="nav-item nav-link" href="{{ url_for('lister.logout') }}">Log Out</a>
            </div>
        </div>
    </nav>

    <!-- View lists that have been created-->
    <div class="container items">
        <div class="form-group float-right">
            <!-- Trigger the modal with add item button -->
            <button class="btn btn-success" data-toggle="modal" data-target="#myModal">
                Create New List
            </button>
        </div>
        {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
        <div class="alert alert-success alert-dismissable offset-3 col-6">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> {{ message }}
        </div>
        <!--end of flash message-->
        {% endfor %} {% endif %} {% endwith %}

        <!--error -->
        {% if error %}
        <div class="d-flex justify-content-center alert alert-danger alert-dismissable offset-3 col-6">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <p class="error">{{ error }}</p>
        </div>
        {% endif %}
        <!--end of error-->

        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">New List</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <!--modal body-->
                    <div class="modal-body">
                        <form class="form-horizontal" action="{{ url_for('lister.add_list') }}" method="POST">
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="name">Name</label>

                                        <div class="col">
                                            <input class="form-control" id="name" name="name" placeholder="List Name">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="notify_date">Date</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" type="date" id="notify_date" name="notify_date" placeholder="Remind me on this date" required>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <input type="submit" class="btn btn-success" value="Save">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {% if shoppinglists %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Remind-me Date</th>
                    <th> Date Modified </th>
                    <th colspan="2" class="text-md-center">Action</th>
                </tr>
            </thead>

            <tbody>
                {% for id, shoppinglist in shoppinglists.items() %}
                <tr>
                    <td>
                        <a href="{{ url_for('lister.items', list_id=shoppinglist.list_id) }}">
                                {{ shoppinglist.name }}
                            </a>
                    </td>
                    <td>{{ shoppinglist.notify_date }}</td>
                    <td> {{ shoppinglist.date_modified }}</td>
                    <td class="text-right">
                        <a href="{{ url_for('lister.edit_list', list_id=shoppinglist.list_id) }}">edit</a>
                    </td>

                    <td class="text-right">
                        <a href="{{ url_for('lister.delete_list', list_id=shoppinglist.list_id) }}">delete </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="items">

            <h1 class="text-center text-color">
                You have no shopping lists yet!
            </h1>
        </div>
        {% endif %}
    </div>
</body>
{% endblock %}